// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TZPU.Services.ProductAPI.DbContexts;

#nullable disable

namespace TZPU.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContexts))]
    [Migration("20230604201747_AddSeedsToDatabase")]
    partial class AddSeedsToDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.4.23259.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TZPU.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = ".NET",
                            Description = " Master the fundamentals of .NET programming and learn how to create .NET projects with this .NET Programming Certification Course. You’ll get introduced to the .NET space and coding with C#, including Visual Studio and WinForms, preparing you for a successful career.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = ".NET Course",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Python",
                            Description = " Learn to Program and Analyze Data with Python. Develop programs to gather, clean, analyze, and visualize data.",
                            ImageUrl = "https://placehold.co/602x402",
                            Name = "Python Course",
                            Price = 13.99
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "C++",
                            Description = " Learn C++ — a versatile programming language that’s important for developing software, games, databases, and more.",
                            ImageUrl = "https://placehold.co/601x401",
                            Name = "C++ Course",
                            Price = 10.99
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "React",
                            Description = "Learn basics of React.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "React Course",
                            Price = 15.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
