// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TZPU.Services.ShoppingCardAPI.DbContexts;

#nullable disable

namespace TZPU.Services.ShoppingCardAPI.Migrations
{
    [DbContext(typeof(AppDbContexts))]
    partial class AppDbContextsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.4.23259.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TZPU.Services.ShoppingCardAPI.Models.CardDetails", b =>
                {
                    b.Property<int>("CardDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardDetailsId"));

                    b.Property<int>("CardHeaderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("CardDetailsId");

                    b.HasIndex("CardHeaderId");

                    b.ToTable("CardDetails");
                });

            modelBuilder.Entity("TZPU.Services.ShoppingCardAPI.Models.CardHeader", b =>
                {
                    b.Property<int>("CardHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardHeaderId"));

                    b.Property<string>("CouponCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardHeaderId");

                    b.ToTable("CardHeaders");
                });

            modelBuilder.Entity("TZPU.Services.ShoppingCardAPI.Models.CardDetails", b =>
                {
                    b.HasOne("TZPU.Services.ShoppingCardAPI.Models.CardHeader", "CardHeader")
                        .WithMany()
                        .HasForeignKey("CardHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardHeader");
                });
#pragma warning restore 612, 618
        }
    }
}
